import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import StoreProvider from './StoreProvider'
import "@/assets/styles/home.scss"


//  image
import Image from 'next/image'
import imageCar from "@/assets/images/Group 3.png"

// icon 
import { GrNext } from "react-icons/gr";
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  banner,
  shop,
}: {
  children: React.ReactNode,
  banner: React.ReactNode
  shop: React.ReactNode
}) {

  return (
    <StoreProvider>
      <html lang="en" className='h-full'>
        <body className={cn("w-full h-full overflow-hidden", inter.className)}>
          {children}

        </body>
      </html>
    </StoreProvider>
  )
}
